remove-rv-integrations-checks = true
enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "ReVanced/revanced-cli"
patches-source = "ReVanced/revanced-patches"
rv-brand = "ReVanced"
riplib = false
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
module-prop-name = "instagram-miguvt"
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
# archive-dlurl = "https://archive.org/download/apks-miguvt/apks/com.instagram.android/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
build-mode = "module"
arch = "arm64-v8a"

[YouTube-Extended]
app-name = "Youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
module-prop-name = "youtube-miguvt"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/apks-miguvt/apks/com.google.android.youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
build-mode = "module"

[Photos]
app-name = "Google Photos"
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
excluded-patches = "'Restore hidden 'Back up while charging' toggle'"
