remove-rv-integrations-checks = true
enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "ReVanced/revanced-cli"
patches-source = "ReVanced/revanced-patches"
rv-brand = "ReVanced"
riplib = false
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YouTube-Extended]
app-name = "Youtube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
build-mode = "apk"

[Spotify]
app-name = "Spotify"
uptodown-dlurl = "https://spotify.uptodown.com/android"
build-mode = "apk"
